-- 코드를 입력하세요
SELECT YEAR(os.SALES_DATE) AS YEAR,
       MONTH(os.SALES_DATE) AS MONTH,
       ui.GENDER AS GENDER,
       COUNT(DISTINCT os.USER_ID) AS MEMBER_COUNT
FROM USER_INFO ui
INNER JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID
WHERE ui.GENDER IS NOT NULL -- 성별 정보가 있는 경우만 포함
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER
ORDER BY YEAR, MONTH, GENDER;
